name:                hlisp
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hlisp#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5 && < 0.6
  - parsec >= 3.1 && < 4

executables:
  hlisp:
    source-dirs:      src
    main:             Main.hs
